server:
  port: 8080
spring:
  application:
    name: "demo_jwt"
  devtools:
    add-properties: false
  http:
    codecs:
      log-request-details: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: demo_webflux
    username: postgres
    password: postgres
    schema: public

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    reactor.netty.http.server.HttpServerOperations: INFO

bezkoder:
  app:
    jwtSecret: TuClaveSuperSecreta1234567890abcdef
    jwtExpirationMs: 3600000 # 1 hora
    jwtRefreshExpirationMs: 604800000 # 7 días